/**
 * Find the difference
 * Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
 */

#include <iostream>
#include <vector>
using namespace std;

namespace find_the_difference {
class Solution {
public:
    char findTheDifference(string s, string t) {
        vector<int> smap(26, 0), tmap(26, 0);
        for (int i = 0; i < s.size(); i++) {
            smap[s[i] - 'a']++;
        }
        for (int j = 0; j < t.size(); j++) {
            tmap[t[j] - 'a']++;
        }
        char ans;
        for (int i = 0; i < 26; i++) {
            if (smap[i] < tmap[i]) {
                ans = i + 'a';
                break;
            }
        }
        return ans;
    }
};
}
